name: Check that app dosent have lint/prettier warnings or errors
on:
  pull_request:
    branches:
      - master
jobs:
  lint-prettier-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        run: npm ci
      - name: Check that app has no lint warnings or errors
        run: npm run lint
      - name: Check that app has no prettier errors
        run: npm run prettier-check
