name: Check that app dosent have lint warnings or errors
on:
  push:
    branches:
      - master
jobs:
  prettier-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v2.2
        with:
          prettier_options: --write  ./{src,functions}/**/**.{ts,tsx,js,jsx,less,css} --write --single-quote
          branch: ${{ github.head_ref }}
          commit_message: Prettified code from github actions
